---
- hosts: web
  become: true
  vars:
    http_port: 80
  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: true
